### ISSUE TITLE
最新的代码报这个错误：ImportError: Unable to find zbar shared library

### ISSUE THREAD

**Issue by codenoob111** [LibraHp/GetQzonehistory#11]

**Comment by codenoob111** [comment]
![Uploading QQ20240911-141623.png…]()

**Comment by codenoob111** [comment]
![Uploading QQ20240911-141623.png…]()

**Comment by yellowsae** [comment]
如果是 window 环境： 安装这个 [https://www.microsoft.com/zh-cn/download/details.aspx?id=40784下载vcredist_x64.exe并安装](https://www.microsoft.com/zh-cn/download/details.aspx?id=40784%E4%B8%8B%E8%BD%BDvcredist_x64.exe%E5%B9%B6%E5%AE%89%E8%A3%85)

Linux 环境安装 apt-get install libzbar0

**Comment by whl0725** [comment]
> 如果是window环境：安装这个[https://www.microsoft.com/zh-cn/download/details.aspx?id=40784下载vcredist_x64.exe并安装](https://www.microsoft.com/zh-cn/download/details.aspx?id=40784%E4%B8%8B%E8%BD%BDvcredist_x64.exe%E5%B9%B6%E5%AE%89%E8%A3%85)
> 
> Linux 环境安装`apt-get install libzbar0`

<img width="1280" alt="6bff50aebedb7558cb8b568026da69b" src="https://github.com/user-attachments/assets/bbc064b0-e3b5-4419-a465-5c200bcb5524">
您这个不可以用呀

**Comment by LibraHp** [comment]
问题就在于你安装的时候 他把后边的文字也识别为了链接[https://www.microsoft.com/zh-cn/download/details.aspx?id=40784](https://www.microsoft.com/zh-cn/download/details.aspx?id=40784

**Comment by codenoob111** [comment]
报错的是我用mac系统，昨晚用windows系统完美运行了
