### ISSUE TITLE
提示：Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by yfzu** [LibraHp/GetQzonehistory#118]
Expecting value: line 1 column 1 (char 0)，请问解决办法

**Comment by Liuwwhh** [comment]
遇到同样问题，请解决

**Comment by yfzu** [comment]
上午还是好用的来着，然后下午不好用了，麻烦作者啦，谢谢

**Comment by GuanyaZhou1** [comment]
遇到同样问题，麻烦作者啦

**Comment by wwweeeeiii** [comment]
同问

**Comment by bigCongee** [comment]
https://github.com/LibraHp/GetQzonehistory/pull/112
修改UA即可正常使用,参考这位大哥的pull

**Comment by yfzu** [comment]
> #112 修改UA即可正常使用,参考这位大哥的pull

我试一下

**Comment by yfzu** [comment]
> #112 修改UA即可正常使用,参考这位大哥的pull
好用了 谢谢兄弟

**Comment by yfzu** [comment]
参考楼上#112
