### ISSUE TITLE
改进建议：GUI版本下载的html内容希望可以保存为本地图片文件

### ISSUE THREAD

**Issue by whliao5am** [LibraHp/GetQzonehistory#136]
使用这个工具大部分想将内容保存到本地进行备份，如果还是在下载后的文件中使用tx官方图片API，如果后续API关闭或者改变，这样可能几年后再打开下载的本地html，就会看不见里面的图片了。

我暂时的做法：下载的html浏览器打开后，右键保存选择保存全部网页内容。

感谢开发者的贡献，希望可以后续集成到软件中。

**Comment by zlaazlaa** [comment]
> 使用这个工具大部分想将内容保存到本地进行备份，如果还是在下载后的文件中使用tx官方图片API，如果后续API关闭或者改变，这样可能几年后再打开下载的本地html，就会看不见里面的图片了。
> 
> 我暂时的做法：下载的html浏览器打开后，右键保存选择保存全部网页内容。
> 
> 感谢开发者的贡献，希望可以后续集成到软件中。

已添加该功能：https://github.com/LibraHp/GetQzonehistory/pull/139
