### ISSUE TITLE
M2pro 1.02版本没有办法下载成功，报错UTF-8

### ISSUE THREAD

**Issue by tokenhs** [LibraHp/GetQzonehistory#156]
![image](https://github.com/user-attachments/assets/551562b0-3668-4782-8539-d5834fbbdcd1)

**Comment by Tonyisshady** [comment]
> ![image](https://github.com/user-attachments/assets/551562b0-3668-4782-8539-d5834fbbdcd1)
> 
> 

同求

**Comment by zlaazlaa** [comment]
Mac M系列芯片可以先试试这个，临时编的： https://objects.githubusercontent.com/github-production-release-asset-2e65be/886685557/22725b86-d153-4439-a6db-5aa3e40b8395?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241113%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241113T084658Z&X-Amz-Expires=300&X-Amz-Signature=d37d884f605af88b0b37732325090f1c44a56b619a48382747de9bbd9354c198&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dmain&response-content-type=application%2Foctet-stream

**Comment by zlaazlaa** [comment]
> Mac M系列芯片可以先试试这个，临时编的：https://github.com/zlaazlaa/GetQzonehistory/releases/tag/mac

已更新，请重新下载
