### ISSUE TITLE
扫码登陆后左下角有报错提示

### ISSUE THREAD

**Issue by MinYu5263** [LibraHp/GetQzonehistory#188]
Windows环境下，扫码登陆后左下角报错，报错信息如图
![error](https://github.com/user-attachments/assets/7b4a9d8b-ef82-4a66-8549-0ef2aa23cad3)

**Comment by heidiansama** [comment]
登录错了就不要登录啊 非要登录才行？傻逼嘛

**Comment by MinYu5263** [comment]
> 登录错了就不要登录啊 非要登录才行？傻逼嘛

你是哪冒出来的奇葩傻逼玩意？不登陆你看你妈的数据呢？
