### ISSUE TITLE
说说列表打不开

### ISSUE THREAD

**Issue by Samiya321** [LibraHp/GetQzonehistory#19]
检测到错误</summary><removedParts><removedPart>被替换的部件: 有 XML 错误的 /xl/worksheets/sheet1.xml。 xml 字符非法。

**Comment by LibraHp** [comment]
可以把对应的表格文件发一下吗

**Comment by 0x3344** [comment]
刚刚发现也有这个问题，查了下那个sheet1文件中含有xml的非法字符 `&#65535;` 删除了这个字符就能正常打开了
