### ISSUE TITLE
能回复以前的留言吗

### ISSUE THREAD

**Issue by TangerineSea** [LibraHp/GetQzonehistory#200]

**Comment by caoqifang** [comment]
人家这是爬数据，回复你麻痹

**Comment by brshengpush** [comment]
> 人家这是爬数据，回复你麻痹

哥们 你笑s我了  别这么大火气 他可能不懂 hahahha

**Comment by brshengpush** [comment]
留言还在的话  你就到你空间里回复就好了

**Comment by caoqifang** [comment]
> 留言还在的话 你就到你空间里回复就好了

他的意思应该是恢复，打错字打成回复了

**Comment by TangerineSea** [comment]
> 人家这是爬数据，回复你麻痹

用你逼逼？傻逼东西？吃你妈逼了在这秀存在感？

**Comment by caoqifang** [comment]
> > 人家这是爬数据，回复你麻痹
> 
> 用你逼逼？傻逼东西？吃你妈逼了在这秀存在感？

嗯，操你妈，我就是舔了你妈的疯狗逼了，你妈逼劲太大，逼不得已出此下策卸劲，要怪就怪你妈吧，傻逼
