### ISSUE TITLE
点击exe文件运行没有反应

### ISSUE THREAD

**Issue by women17sui** [LibraHp/GetQzonehistory#206]
GetQzoneHistory.exe点击运行没有反应,下载源码到本地很多包导入不进来,我是java程序员,不会python

**Comment by password122213** [comment]
> GetQzoneHistory.exe点击运行没有反应，下载源码到本地很多包导入不进来，我是java程序员，不会python
使用fidder看一下接口返回的数据是啥，我最一开始是不成功的，后来改了user-agent，很有可能是被反扒了，我的目前是可以用的

**Comment by MinYu5263** [comment]
你一个程序员难道没有独立解决问题的能力，主页有Redme，B站有视频，你不知道看？你会Java就只能会Java，不会看看python

**Comment by women17sui** [comment]
> 你一个程序员难道没有独立解决问题的能力，主页有Redme，B站有视频，你不知道看？你会Java就只能会Java，不会看看python
有没有一种可能,我是说可能,我就是偶然在b站发现这个的,视频和readme我都看了,还是解决不了问题我才求助的.另外,请你少一点戾气,一副好为人师的样子真的令人反感.
