### ISSUE TITLE
不能爬取删除的数据，等多个问题

### ISSUE THREAD

**Issue by silent-wuhen** [LibraHp/GetQzonehistory#241]
问题一：
二维码只能在CMD扫码登录，在pycharm运行无法扫码（问AI说的是qrcode库解决，不知真假）：
![001](https://github.com/user-attachments/assets/e49c909b-ffc4-4460-bf9c-d99c3db30312)

问题二
只能爬没有删除的说说，删除的看不见。注：B站上看到说能爬：https://www.bilibili.com/video/BV1izmWYnELN

问题三：
第二次运行的代码时候出现如下情况，无法获取数据（指的是需要接近6个小时），在第二次使用软件中直接显示的是没有数据：
![002](https://github.com/user-attachments/assets/8e073180-d02b-49d2-a1fc-529a987edfc2)

**Comment by Cz1544252489** [comment]
对于你的问题三，这个50001应该是个错误，不同人都会出现这个。

**Comment by silent-wuhen** [comment]
> 对于你的问题三，这个50001应该是个错误，不同人都会出现这个。

好的谢谢你，作者以前的B站视频评论中好像说的是换一个时间去爬
