### ISSUE TITLE
安卓設備無法識別掃描二維碼

### ISSUE THREAD

**Issue by E-sion** [LibraHp/GetQzonehistory#3]
二維碼belike：
![image](https://github.com/user-attachments/assets/f6eef0a3-5b4d-40da-b02e-00549d7ea39b)
試過了很多個識別二維碼的軟件，均無法識別

**Comment by LibraHp** [comment]
可以在temp目录下找到生成的二维码，或者在QR函数中添加im.show()均可以解决控制台二维码输出不对齐的问题
