### ISSUE TITLE
一只卡在认证中

### ISSUE THREAD

**Issue by ruinmi** [LibraHp/GetQzonehistory#41]
![image](https://github.com/user-attachments/assets/09a30000-3fc4-48c3-932f-6383a5362483)

**Comment by LibraHp** [comment]
网络环境问题 连个热点试试

**Comment by ruinmi** [comment]
> 网络环境问题 连个热点试试

用的命令行版就正常登录，这个gui版就不行，话说gui版代码提交了嘛，我不太了解python，我把源码运行了还是命令行版

**Comment by LibraHp** [comment]
新版本代码在gui分支下 不过如果想要跑的话 需要安装flutter环境
