### ISSUE TITLE
[求助]登录一直提示“用户取消登录”

### ISSUE THREAD

**Issue by BlackTitle** [LibraHp/GetQzonehistory#46]
![QQ20240930-014641](https://github.com/user-attachments/assets/0d9dafbf-8e12-4e4e-a96a-da7613d43ccd)

网络环境没问题，其他账号可以登录
源码版和GUI版都试了，都登录不进去
这个大概是为啥出现的？

**Comment by LibraHp** [comment]
有尝试换过网络没有

**Comment by BlackTitle** [comment]
> 有尝试换过网络没有

尝试过，PC和手机除了两个网络、PC全局梯子代理都试过，全显示这个提示

**Comment by LibraHp** [comment]
如果网名里面有特殊字符 需要改一下网名

**Comment by BlackTitle** [comment]
> 如果网名里面有特殊字符 需要改一下网名

正解，感谢。建议在程序页面标注一下

**Comment by luke358** [comment]
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/37307dcb-a11a-4557-9c48-6620024da156" />
这里改掉，我发现是因为乱码的问题，r.text里面的登录成功是乱码的，导致这个匹配一直失败
