### ISSUE TITLE
报错out of range

### ISSUE THREAD

**Issue by iduee** [LibraHp/GetQzonehistory#48]
报错:获取消息时发生错误
刚开始有特殊字符，修改名字为123后又获取两次均失败
![Screenshot_2024-09-30-14-58-27-525_com oray sunlogin-edit](https://github.com/user-attachments/assets/23fc368e-3296-45fa-94b1-64886a4a9fc6)

**Comment by LibraHp** [comment]
已修复

**Comment by LibraHp** [comment]
还是使用1.0.2的release就好

**Comment by LibraHp** [comment]
我又重新上传了1.0.2

**Comment by iduee** [comment]
> 我又重新上传了1.0.2
我的小号在上一个版本可以正常使用，但是这个号不行，更新版本后无法获取说说
![Screenshot_2024-09-30-16-38-37-568_com oray sunlogin-edit](https://github.com/user-attachments/assets/10b6b0a8-6053-4a32-a4f8-44f0dd6229f0)
