### ISSUE TITLE
mac登陆后没有任何数据，之前是因为ID特殊文字，更改后还是没有哎，两个Mac版本都试了求指导

### ISSUE THREAD

**Issue by Alfredbear** [LibraHp/GetQzonehistory#54]
#Mac打开无任何数据
![Uploading 截屏2024-10-14 00.45.23.png…]()

**Comment by Wi-ni** [comment]
我也是，m2芯片，卸载重装了三次，都是所有数据全为零。
<img width="811" alt="截屏2024-10-14 01 34 43" src="https://github.com/user-attachments/assets/ea941bca-69a8-4ce2-9b42-79a61eb48399">
<img width="817" alt="截屏2024-10-14 01 34 51" src="https://github.com/user-attachments/assets/29c0e67f-423c-4ca3-b710-41e68791852e">
<img width="818" alt="截屏2024-10-14 01 34 29" src="https://github.com/user-attachments/assets/e0c761a1-56bb-4ba2-86d2-806d66d14359">

**Comment by Alfredbear** [comment]
就是像楼上那位，我也是M2
