### ISSUE TITLE
i can't run it

### ISSUE THREAD

**Issue by Xc1Ym** [LibraHp/GetQzonehistory#6]
`FileNotFoundError: Could not find module 'C:\Program Files\Python312\Lib\site-packages\pyzbar\libzbar-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

![image](https://github.com/user-attachments/assets/daedf3ed-233f-44e7-9ccd-4ce6bb821f1f)

**Comment by detaide** [comment]
你可以在https://www.microsoft.com/zh-cn/download/details.aspx?id=40784下载vcredist_x64.exe并安装

**Comment by Xc1Ym** [comment]
thank u
