### ISSUE TITLE
可能是我有点小白的问题吧，安装了pyzbar还是会报错

### ISSUE THREAD

**Issue by xuliangyi3** [LibraHp/GetQzonehistory#63]
![Snipaste_2024-10-20_22-00-14](https://github.com/user-attachments/assets/6fc5865d-9f9c-401f-bf61-bd60a924ebc3)

**Comment by zeal2000** [comment]
我也是。。。。

**Comment by LibraHp** [comment]
可以下载releases里面打包好的 就不会出现这个问题

**Comment by Akihi11** [comment]
https://www.microsoft.com/zh-cn/download/details.aspx?id=40784
下一个这个就可以了
