### ISSUE TITLE
获取不到任何内容，v1.0.2，windows23H2

### ISSUE THREAD

**Issue by JimmyHuk** [LibraHp/GetQzonehistory#71]
![image](https://github.com/user-attachments/assets/4679b975-191a-4ef6-825c-9407a48cf0c9)

重启软件，多次退出重新登录，都没有数据；偶尔能爬到最近互动的一个好友，但是没有其他数据了。

=======================================
24.11.15 版本已解决

**Comment by waiyouyou** [comment]
我也是

**Comment by LibraHp** [comment]
换个设备试试 现在已知的问题是13年之前发的会导致获取为0条 13年之后0条的多半是因为网络或者环境问题，先用一下1.0.1试一下

**Comment by lixingyun666** [comment]
13年之前的账号我可以获得记录，14年之后的号登录进去就是没有一条记录。

**Comment by wind056** [comment]
俺也一样

**Comment by chern91552** [comment]
昵称改成没有特殊字符的就行了

**Comment by yin1223** [comment]
老哥，还是不行呀
